### ISSUE TITLE
QUESTION: Will future versions break older compressed strings?

### ISSUE THREAD

**Issue by LauDijksterhuis** [skipness/lzstring-dart#10]
Hello!

Your package looks amazing, but I have a question before using it in production environment.

I am looking for a way to store some value's (like really big text files) on my server and send them via an API to the client (flutter app). To reduce data transfer, I was wondering if it is safe to use this package to compress the files (store them for maybe 3 years) and retrieve them at any moment.

With safe I mean: will the algorithm change in the future? And therefor make the files unreadable when updating the package?

Thank you in advance!
Lau

**Comment by skipness** [comment]
Hi Lau, Merry Christmas and sorry for late response! 
This package is ported from a [Javascript](https://github.com/pieroxy/lz-string) version which hasn't been updated [since 2015](https://github.com/pieroxy/lz-string/releases/tag/1.4.4) so I can say it should be stable to use(weird to say that😂). I would also recommend you to look for more compression package as replacement so that you can swap it in case this package have any issues in production environment.

**Comment by LauDijksterhuis** [comment]
@skipness 

Merry (belated) Christmas to you as well!
Thank you for your response, with over 8 years of reliability I will take a shot at it. 😄

I wish you a happy new year!
